kind: Service
apiVersion: v1
metadata:
  name: rg-server
  labels:
    app: rg-server
spec:
  type: ClusterIP
  selector:
    app: rg-server
  ports:
  - name: grpc
    port: 8079
    targetPort: grpc

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rg-server
  labels:
    app: rg-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rg-server
  template:
    metadata:
      labels:
        app: rg-server
    spec:
      containers:
      - name: rg-server
        image: routeguide
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: rg-server-config
        command:
        - /bin/bash
        - "-c"
        - |
          /rg-server -port ${SERVER_PORT} -fault-percent ${FAULT_PERCENT}
        ports:
        - name: grpc
          containerPort: 8079
        readinessProbe:
          initialDelaySeconds: 5
          exec:
            command:
            - /bin/bash
            - "-c"
            - |
              /grpc_health_probe -addr=:${SERVER_PORT} -service=routeguide.RouteGuide
        livenessProbe:
          initialDelaySeconds: 10
          exec:
            command:
            - /bin/bash
            - "-c"
            - |
              /grpc_health_probe -addr=:${SERVER_PORT} -service=routeguide.RouteGuide

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rg-server-config
  labels:
    app: rg-server
data:
  SERVER_PORT: "8079"
  FAULT_PERCENT: "0.0"

---
kind: Pod
apiVersion: v1
metadata:
  name: rg-client
  labels:
    app: rg-client
spec:
  restartPolicy: OnFailure
  containers:
  - name: rg-client
    image: routeguide
    imagePullPolicy: Never
    command:
    - /bin/bash
    - "-c"
    - |
      /rg-client -server ${SERVER_HOST}:${SERVER_PORT} -timeout ${GRPC_TIMEOUT} -mode ${MODE} -n ${MAX_REPEAT} -api ${REMOTE_API} -n ${MAX_REPEAT}
    envFrom:
    - configMapRef:
        name: rg-client-config

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rg-client-config
  labels:
    app: rg-client
data:
  SERVER_HOST: rg-server
  SERVER_PORT: "8079"
  GRPC_TIMEOUT: 20s
  MODE: repeatn
  MAX_REPEAT: "20"
  REMOTE_API: GetFeature
  ENABLE_LOAD_BALANCING: "true"
  RESOLVER_MODE: "dns"
