apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: rg-server
spec:
  service: rg-server
  backends:
  - service: rg-server-green
    weight: 500m
  - service: rg-server-blue
    weight: 500m
