kind: Service
apiVersion: v1
metadata:
  name: rg-server
  labels:
    app: rg-server
spec:
  type: ClusterIP
  selector:
    app: rg-server
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rg-server
  labels:
    app: rg-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rg-server
  template:
    metadata:
      labels:
        app: rg-server
    spec:
      containers:
      - name: rg-server
        image: routeguide
        imagePullPolicy: Never
        command:
        - /rg-server
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: FAULT_PERCENT
          value: "0.0"
        ports:
        - name: grpc
          containerPort: 8080

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rg-client
  labels:
    app: rg-client
spec:
  restart: Never
  selector:
    matchLabels:
      app: rg-client
  template:
    metadata:
      labels:
        app: rg-client
    spec:
      containers:
      - name: rg-client
        image: routeguide
        imagePullPolicy: Never
        command:
        - /rg-client
        env:
        - name: SERVER_HOST
          value: rg-server
        - name: SERVER_PORT
          value: "8080"
        - name: GRPC_TIMEOUT
          value: "20s"
        - name: MODE
          value: "REPEATN"
